service: metadata-provider-serverless

plugins:
  - serverless-plugin-typescript 
  - serverless-plugin-optimize
  - serverless-offline
  # - serverless-plugin-warmup

# custom:
#   # Enable warmup on all functions (only for production and staging)
#   warmup:      
#       - production
#       - staging

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  profile: metadata-provider-deployer
  memorySize: 1024
  timeout: 900
  environment:

package:
  individually: true

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
