org: buooy
console: true
service: metadata-provider-serverless

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

# custom:
#   # Enable warmup on all functions (only for production and staging)
#   warmup:
#       - production
#       - staging

custom:
  customDomain:
    domainName: json.buooy.xyz
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false

provider:
  name: aws
  runtime: nodejs12.x
  stage: v1
  region: ap-southeast-1
  profile: metadata-provider-deployer
  memorySize: 1024
  timeout: 900
  environment:
    S3_ACCESS_KEY_ID: ${ssm:/metadata-provider-production/S3_ACCESS_KEY_ID, file(./env.localhost.yml):S3_ACCESS_KEY_ID}
    S3_SECRET_ACCESS_KEY: ${ssm:/metadata-provider-production/S3_SECRET_ACCESS_KEY, file(./env.localhost.yml):S3_SECRET_ACCESS_KEY}
    S3_ENDPOINT: ${ssm:/metadata-provider-production/S3_ENDPOINT, file(./env.localhost.yml):S3_ENDPOINT}
    S3_BUCKET: ${ssm:/metadata-provider-production/S3_BUCKET, file(./env.localhost.yml):S3_BUCKET}
    S3_JSON_BUCKET: ${ssm:/metadata-provider-production/S3_JSON_BUCKET, file(./env.localhost.yml):S3_JSON_BUCKET}

package:
  individually: true

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
